### ISSUE TITLE
SingleIOProcessor의 감시할 kevent 종류 분기 처리

### ISSUE THREAD

**Issue by Yonaim** [Yonaim/42_webserv#9]
현재 SingleIOProcessor는 kevent를 무조건 R/W 둘다 감시하고 있는데요, 그렇기 때문에 기존에 이미 파일이 존재하는 path로 `POST`를 시도할 시에도 Read 이벤트 발생이 감지되어 해당 fd를 `open()`할 때의 옵션과 관계없이 `read()` 시도를 한다는 문제점이 있습니다.
(`WRONLY` 옵션으로 발급받은 fd인데 `read`시도를 하게 되어 오류가 발생합니다.)
그래서 감시할 이벤트의 종류를 옵션으로 받는 SingleIOProcessor 생성자를 추가로 만들고, kqueue에 넣는 kevent도 해당 변수 값에 따라 분기 처리했으면 합니다.

**Comment by gitubanana** [comment]
제가 처리하겠습니당~
